package-lock.json, package.json, src/components/Modal/subComponents/ModalFooter/index.tsx
=> [MI-2200] Fix modal styling

package-lock.json, package.json, src/components/AutoSuggest/index.tsx, src/components/Modal/subComponents/ModalFooter/index.tsx, src/styles/components/_autoSuggest.scss
1. Fix modal buttons
2. Remove the icon from auto suggest component
3. Change the size of the placeholder
=> [MI-2236] Fix bugs in mm ui library

.vscode/settings.json, src/components/Button/Button.component.tsx, src/components/Button/Button.d.ts, src/components/Button/Button.stories.tsx, src/components/Button/Button.styles.ts, src/components/Button/index.ts, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
[MI-2220](https://brightscout.atlassian.net/browse/MI-2220)
- Created Button Component
=> MI-2220: Button Component

src/components/Switch/Switch.component.tsx, src/components/Switch/Switch.d.ts, src/components/Switch/Switch.stories.tsx, src/components/Switch/Switch.styles.ts, src/components/Switch/index.ts, src/index.tsx, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
[MI-2269](https://brightscout.atlassian.net/browse/MI-2269)
- Created Switch Component
=> MI-2269: Switch

.storybook/preview.js, src/assets/icons/spinner.svg, src/components/Icon/Icon.map.ts, src/components/Spinner/Spinner.component.tsx, src/components/Spinner/Spinner.d.ts, src/components/Spinner/Spinner.stories.tsx, src/components/Spinner/Spinner.styles.ts, src/components/Spinner/index.ts, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
Ticket Link
[MI-2263](https://brightscout.atlassian.net/browse/MI-2263)
Description
- Created Spinner Component
Screenshots
=> MI-2263: Spinner Component

.storybook/preview.js, src/assets/icons/spinner.svg, src/components/Icon/Icon.map.ts, src/components/LinearProgress/LinearProgress.component.tsx, src/components/LinearProgress/LinearProgress.d.ts, src/components/LinearProgress/LinearProgress.stories.tsx, src/components/LinearProgress/LinearProgress.styles.ts, src/components/LinearProgress/index.ts, src/components/Spinner/Spinner.component.tsx, src/components/Spinner/Spinner.d.ts, src/components/Spinner/Spinner.stories.tsx, src/components/Spinner/Spinner.styles.ts, src/components/Spinner/index.ts, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
Ticket Link
[MI-2268](https://brightscout.atlassian.net/browse/MI-2268)
Description
Created LinearProgress Component
Screenshots
=> MI-2268: LinearProgress Component

src/components/LinearProgress/LinearProgress.component.tsx, src/components/LinearProgress/LinearProgress.d.ts, src/components/LinearProgress/LinearProgress.stories.tsx, src/components/LinearProgress/LinearProgress.styles.ts, src/components/LinearProgress/index.ts
Ticket Link
[MI-2268](https://brightscout.atlassian.net/browse/MI-2268)
Description
Created LinearProgress Component
Screenshots
=> MI 2268: LinearProgress Component

src/components/MenuItem/MenuItem.component.tsx, src/components/MenuItem/MenuItem.d.ts, src/components/MenuItem/MenuItem.stories.tsx, src/components/MenuItem/MenuItem.styles.ts, src/components/MenuItem/index.ts, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
Ticket Link
[MI-2270](https://brightscout.atlassian.net/browse/MI-2270)
Description
Created MenuItem Component
Screenshots
=> MI-2270: MenuItem Component

src/components/TextArea/TextArea.component.tsx, src/components/TextArea/TextArea.d.ts, src/components/TextArea/TextArea.stories.tsx, src/components/TextArea/TextArea.styles.ts, src/components/TextArea/index.ts
Ticket Link
[MI-2275](https://brightscout.atlassian.net/browse/MI-2275)
Description
Created Text area Component
Screenshots
**Default state**
**Default state on focus**
**Default state on value present**
**Default state on value present and focused**
**Error state**
**Error state focused**
**Readonly state**
**Readonly state with value**
=> MI-2275: Textarea component

src/components/Popover/Popover.component.tsx, src/components/Popover/Popover.d.ts, src/components/Popover/Popover.stories.tsx, src/components/Popover/Popover.styles.ts, src/components/Popover/index.ts
Ticket Link
[MI-2322](https://brightscout.atlassian.net/browse/MI-2322)
Description
Created Popover component
Screenshots
=> MI 2322: Popover component

src/components/Skeleton/Skeleton.component.tsx, src/components/Skeleton/Skeleton.d.ts, src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.styles.ts, src/components/Skeleton/index.ts, src/styles/colorsForJs.module.scss
Ticket Link
[MI-2325](https://brightscout.atlassian.net/browse/MI-2325)
Description
Created Skeleton component
Screenshots
**Circular Skeleton**
**Rectangular Skeleton**
**Rectangular Skeleton with border radius**
**Passing in dimensions as string**
=> MI:2325: Skeleton component

src/components/Radio/Radio.component.tsx, src/components/Radio/Radio.d.ts, src/components/Radio/Radio.stories.tsx, src/components/Radio/Radio.styles.ts, src/components/Radio/index.ts
Ticket Link
[MI-2327](https://brightscout.atlassian.net/browse/MI-2327)
Description
Created Radio Component
Screenshots
**Default state**
**Default on state**
**Error state**
**Error on state**
**Disabled state**
**Two radio state**
=> MI 2327: Radio Component

src/components/Dialog/Dialog.stories.tsx, src/components/Modal/Modal.stories.tsx, src/components/Radio/Radio.stories.tsx
=> MI-2357: Changed show value in Modal & Dialog and added space in Radio

README.md, package-lock.json, package.json
[MI-2357](https://brightscout.atlassian.net/browse/MI-2357)
- Added storybook link in readme file
- Updated mm-ui-lib version
=> MI-2357: Added storybook link in readme file

package-lock.json, package.json, src/styles/components/_confirmationDialog.scss
=> [MI-2459] Fix confirmation dialog delete button css

package-lock.json, package.json, src/components/Buttons/MenuButtons/index.tsx, src/components/Card/Subscription/index.tsx, src/styles/base/_utils.scss
Bump the version of the library
Added classname prop in the Menu button component and passed its value from subscription card context menu
Removed a duplicate style from utils.scss
=> [MI-2604] Fixed the color of the Delete option in the subscription card context menu

package-lock.json, package.json, src/styles/components/_autoSuggest.scss, src/styles/components/_dropdown.scss
[Issue: #160](https://github.com/mattermost/mattermost-plugin-servicenow/issues/160)
=> [MI-2635]:Modal dropdowns started showing background color on hovering on options on version 5.37.3 as well.

src/assets/icons/arrow_left.svg, src/components/Button/Button.d.ts, src/components/Button/Button.stories.tsx, src/components/Button/Button.styles.ts, src/components/Icon/Icon.map.ts, src/components/NoData/NoData.styles.ts
####Ticket ID: 
https://brightscout.atlassian.net/browse/MI-2620
Create Text variant of button component
=> [MI-2620-text-button]: Create text button variant

src/components/Tabs/Tabs.component.tsx, src/components/Tabs/Tabs.d.ts, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.styles.ts, src/components/Tabs/index.ts, src/index.tsx, src/styles/abstract/_cssVariables.scss, src/styles/colorsForJs.module.scss
[MI-2601](https://brightscout.atlassian.net/browse/MI-2601)
Added reusable tab component.
=> MI-2601: Create Reusable tab component

package-lock.json, package.json, src/components/AutoSuggest/index.tsx, src/styles/components/_autoSuggest.scss
=> [MI-2813]: Added a placeholder for default selected option in autoselector

src/components/List/List.component.tsx, src/components/List/List.d.ts, src/components/List/List.styles.ts, src/components/MMSearch/MMSearch.component.tsx, src/components/MMSearch/MMSearch.d.ts, src/components/MMSearch/MMSearch.stories.tsx, src/components/MenuItem/MenuItem.d.ts, src/components/MenuItem/MenuItem.styles.ts, src/components/NoData/NoData.component.tsx, src/components/NoData/NoData.d.ts, src/components/NoData/NoData.styles.ts, src/components/Tabs/Tabs.styles.ts
https://brightscout.atlassian.net/browse/MI-2867
- Add search label auto-suggest hints
- Add className prop and iconBgColor in NoData
- Centre Align text in NoData
- Fix background colour in Tabs
- Fix Option List Background in MMSearch
- Fix MMSearch option list all options change to from:
=> [MI-2867]: Add search label auto-suggest hints and other style fixes

src/components/Dialog/Dialog.component.tsx, src/components/Dialog/Dialog.d.ts, src/components/Dialog/Dialog.stories.tsx, src/components/Dialog/Dialog.styles.ts
https://brightscout.atlassian.net/browse/MI-2977
- Fix dialog width and position
- Add secondaryActionText prop
=> [MI-2977]: Fix dialog width ,position and add secondaryActionText prop

src/components/Dialog/Dialog.component.tsx, src/components/Dialog/Dialog.d.ts, src/components/List/List.component.tsx, src/components/List/List.d.ts, src/components/MenuItem/MenuItem.component.tsx, src/components/MenuItem/MenuItem.d.ts
Added props for label element and cancel button text
=> [MI-3029]: Added props for label element and cancel button text.

src/components/Input/Input.component.tsx, src/components/Input/Input.d.ts, src/components/Input/Input.stories.tsx, src/components/Input/Input.styles.ts, src/styles/colorsForJs.module.scss
https://brightscout.atlassian.net/browse/MI-2978
- Add size variants for the Input
- Add borderless variant for Input
=> [MI-2978]: Add size and borderless variant

src/assets/icons/check_bold.svg, src/components/CheckBox/CheckBox.component.tsx, src/components/CheckBox/CheckBox.d.ts, src/components/CheckBox/CheckBox.styles.ts, src/components/Icon/Icon.map.ts, src/constants/index.ts
https://brightscout.atlassian.net/browse/MI-2971
- Rebuild the checkbox component
- Add size variants for the checkbox
=> [MI-2971]: Fix checkbox and add size variants

src/components/Modal/Modal.component.tsx, src/components/Modal/subComponents/ModalFooter/ModalFooter.component.tsx, src/components/Modal/subComponents/ModalFooter/ModalFooter.d.ts
Added disabled prop for modal primary button.
=> [MI-3138]: Added disabled prop for modal primary button.
